### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by SensehacK**
- **Please check if the PR fulfills these requirements**

* [x] The commit message follows our guidelines
* [x] I have read the **CONTRIBUTING** document.
* [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by ManasiTayade** [comment]
I have reviewed the code of conduct and it cover all the points for now.

**Comment by SensehacK** [comment]
@ManasiTayade With Pull Requests, if you review it & have approved it. Pull Request would be merged first & then closed.

Unless you have want changes from the PR author you don’t closed it or reject PR.

I’m reopening the PR again, please go through the basics of Github Projects & Workflow I shared the guidelines on ToDo #16 @rtrend96 can help you with that.

**Comment by rtrend96** [comment]
@SensehacK i will look into it

**Review by ManasiTayade — APPROVED** [review]
Ok got it. @SensehacK @rtrend96

**Pull request merged**
